# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QtCore.QSize(1920, 1080))
        MainWindow.setMaximumSize(QtCore.QSize(3840, 2160))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 0, 300, 80))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1240, 80, 620, 700))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("border: 1px solid black;border-radius: 20px;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.figMAC = QtWidgets.QLabel(self.groupBox)
        self.figMAC.setGeometry(QtCore.QRect(300, 40, 300, 200))
        self.figMAC.setStyleSheet("border: none;")
        self.figMAC.setText("")
        self.figMAC.setObjectName("figMAC")
        self.txtMAC = QtWidgets.QLabel(self.groupBox)
        self.txtMAC.setGeometry(QtCore.QRect(40, 40, 200, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.txtMAC.setFont(font)
        self.txtMAC.setStyleSheet("border: none;")
        self.txtMAC.setObjectName("txtMAC")
        self.txtJSON = QtWidgets.QLabel(self.groupBox)
        self.txtJSON.setGeometry(QtCore.QRect(40, 250, 200, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.txtJSON.setFont(font)
        self.txtJSON.setStyleSheet("border: none;")
        self.txtJSON.setObjectName("txtJSON")
        self.figJSON = QtWidgets.QLabel(self.groupBox)
        self.figJSON.setGeometry(QtCore.QRect(300, 250, 300, 200))
        self.figJSON.setStyleSheet("border: none;")
        self.figJSON.setText("")
        self.figJSON.setObjectName("figJSON")
        self.txtOTA = QtWidgets.QLabel(self.groupBox)
        self.txtOTA.setGeometry(QtCore.QRect(40, 460, 200, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.txtOTA.setFont(font)
        self.txtOTA.setStyleSheet("border: none;")
        self.txtOTA.setObjectName("txtOTA")
        self.figOTA = QtWidgets.QLabel(self.groupBox)
        self.figOTA.setGeometry(QtCore.QRect(300, 480, 300, 200))
        self.figOTA.setStyleSheet("border: none;")
        self.figOTA.setText("")
        self.figOTA.setObjectName("figOTA")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1410, 0, 291, 71))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(40)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.txtInfo = QtWidgets.QLabel(self.centralwidget)
        self.txtInfo.setGeometry(QtCore.QRect(30, 80, 1090, 860))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.txtInfo.setFont(font)
        self.txtInfo.setStyleSheet("border: 1px solid black; background: rgb(211, 211, 211);  border-radius: 20px;")
        self.txtInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtInfo.setObjectName("txtInfo")
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(1860, 670, 60, 60))
        self.resetBtn.setStyleSheet("border: none; outline:none; background: none;")
        self.resetBtn.setText("")
        self.resetBtn.setObjectName("resetBtn")
        self.compare_result = QtWidgets.QLabel(self.centralwidget)
        self.compare_result.setGeometry(QtCore.QRect(1860, 670, 60, 60))
        self.compare_result.setStyleSheet("border: none;")
        self.compare_result.setText("")
        self.compare_result.setObjectName("compare_result")
        self.txtAuthor = QtWidgets.QLabel(self.centralwidget)
        self.txtAuthor.setGeometry(QtCore.QRect(1750, 830, 150, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.txtAuthor.setFont(font)
        self.txtAuthor.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAuthor.setObjectName("txtAuthor")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(1210, 830, 520, 110))
        self.logo.setStyleSheet("border: none;")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("./resource/logo.png"))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.gif = QtWidgets.QGroupBox(self.centralwidget)
        self.gif.setGeometry(QtCore.QRect(1750, 890, 150, 40))
        self.gif.setStyleSheet("border: none;")
        self.gif.setTitle("")
        self.gif.setObjectName("gif")
        self.txtGif = QtWidgets.QLabel(self.gif)
        self.txtGif.setGeometry(QtCore.QRect(0, 0, 440, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.txtGif.setFont(font)
        self.txtGif.setStyleSheet("")
        self.txtGif.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGif.setObjectName("txtGif")
        
        self.txtAuthor.raise_()
        self.label.raise_()
        self.groupBox.raise_()
        self.label_5.raise_()
        self.txtInfo.raise_()
        self.resetBtn.raise_()
        self.compare_result.raise_()
        self.logo.raise_()
        self.gif.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bar Code App"))
        self.label.setText(_translate("MainWindow", "系統資訊"))
        self.txtMAC.setText(_translate("MainWindow", "MAC"))
        self.txtJSON.setText(_translate("MainWindow", "JSON"))
        self.txtOTA.setText(_translate("MainWindow", "OTA"))
        self.label_5.setText(_translate("MainWindow", "燒錄狀態"))
        self.txtInfo.setText(_translate("MainWindow", "目標編號: D1:D1:D1:D1:D1:D1\n"
"[2022-04-27 10-04-23]讀取MAC檔案失敗，請檢查檔案。\n"
"FDDD\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG\n"
"GGG"))
        self.txtAuthor.setText(_translate("MainWindow", "製作群"))
        self.txtGif.setText(_translate("MainWindow", "Ken Huang  Mark Chang  Etta Mok"))
